name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      TERM: dumb

    steps:
      - name: Generate Build Number
        shell: bash
        run: echo "Build_Number=$(expr $GITHUB_RUN_NUMBER + 5210)" >> $GITHUB_ENV

      - uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build & Check
        run: |
          ./gradlew --scan --stacktrace \
              spotlessCheck \
              assemble bundle \
              app:lintDebug testDebug

      - name: Upload Build Outputs
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: build-outputs
          path: app/build/outputs

      - name: Upload Build Reports
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: build-reports
          path: app/build/reports
